# **************************************************************************************************************
#
#  Copyright 2020-2026 Robert Bosch GmbH
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
#
# **************************************************************************************************************
#
"""
Delete files within component installation folder under site-packages.

Delete build artefacts in local application folder.

Should be executed separately before the next installation starts.

Goal: Avoid access conflicts with file handles generated by PIP or by custom build backend.
"""

import os
import sys
import logging
import shutil

from config.CRepositoryConfig import CRepositoryConfig # provides repository and environment specific information

logging.basicConfig(level=logging.INFO, stream=sys.stderr)
logger = logging.getLogger(__name__)

# --------------------------------------------------------------------------------------------------------------

SUCCESS = 0
ERROR   = 1

# --------------------------------------------------------------------------------------------------------------

class CInstallation:
    """
Methods to tidy up the installation
    """

    def __init__(self):
        # setup of repository configuration
        self.repository_config = None
        try:
            self.repository_config = CRepositoryConfig(f"{__file__}")
        except Exception as ex:
            logger.critical(str(ex))
            raise


    def delete_previous_build(self):
        """
Delete build artefacts in local application folder.
        """
        setup_build_folder = self.repository_config.Get('SETUPBUILDFOLDER')
        egginfo_folder     = self.repository_config.Get('EGGINFOFOLDER')
        dist_folder        = self.repository_config.Get('SETUPDISTFOLDER')
        for folder in (setup_build_folder, egginfo_folder, dist_folder):
            if os.path.isdir(folder) is True:
                try:
                    shutil.rmtree(folder)
                    logger.info(f"Deleted folder '{folder}'")
                except Exception:
                    logger.warning(f"Skipping to delete folder (in use): '{folder}'")
        return SUCCESS
    # eof def delete_previous_build():

    def delete_previous_installation(self):
        """
Delete files within component installation folder under site-packages.
        """
        installed_package_folder = self.repository_config.Get('INSTALLEDPACKAGEFOLDER')
        cnt_files_with_errors = 0
        if os.path.isdir(installed_package_folder):
            logger.info(f"Cleaning contents of '{installed_package_folder}'")

            for root, dirs, files in os.walk(installed_package_folder, topdown=False):
                # delete files separately
                for name in files:
                    file_path = os.path.join(root, name)
                    try:
                        os.remove(file_path)
                        logger.debug(f"Deleted file: '{file_path}'")
                    except OSError:
                        cnt_files_with_errors = cnt_files_with_errors + 1
                        logger.warning(f"Skipping to delete file (in use): '{file_path}'")

                # delete folders separately (only if empty)
                for name in dirs:
                    dir_path = os.path.join(root, name)
                    try:
                        os.rmdir(dir_path)
                        logger.debug(f"Deleted folder: '{dir_path}'")
                    except OSError:
                        logger.warning(f"Skipping to delete folder (not empty/in use): '{dir_path}'")
            if cnt_files_with_errors > 0:
                logger.info(f"Cleanup finished (but {cnt_files_with_errors} file(s) still exist)")
            else:
                logger.info("Cleanup finished")

        return SUCCESS

    # eof def delete_previous_installation():

# eof class CInstallation:

installation = CInstallation()

installation.delete_previous_installation()
installation.delete_previous_build()

sys.exit(SUCCESS)

