name: Publish robotframework-testsuitesmanagement to PyPI

on:
  push:
    tags:
      - "rel/*.*.*"
      - "rel/*.*.*.*"
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'Release Tag name for creating Github Release'
        required: false
        type: string

jobs:
  build-n-publish:
      name: Build and publish to PyPI
      runs-on: ubuntu-latest
      permissions:
        contents: write

      steps:
        - name: Checkout source
          uses: actions/checkout@v4

        - name: Set up Python
          uses: actions/setup-python@v6
          with:
            python-version: "3.13"

        - name: Install dependencies
          run: |
            sudo apt-get update
            sudo apt-get install -y pandoc
            sudo apt-get install -y texlive-latex-*
            echo "GENDOC_LATEXPATH=$(dirname $(which pdflatex))" >> $GITHUB_ENV
            if [ -f "./requirements_linux.sh" ]; then
              chmod +x ./requirements_linux.sh
              ./requirements_linux.sh
            fi
            python -m pip install --upgrade setuptools build twine wheel GenPackageDoc PythonExtensionsCollection
            if [ -f "./requirements.txt" ]; then
              python -m pip install -r ./requirements.txt
            fi

        - name: Build source and wheel distributions
          run: |
            if [ -d "dist" ]; then
              rm -rf dist
            fi
            if [ -f "./pyproject.toml" ]; then
              if [ -f "./genpackagedoc.py" ]; then
                python -m pip install .
                python genpackagedoc.py
              fi
              python -m build
            elif [ -f "./setup.py" ]; then
              python setup.py sdist bdist_wheel
            else
              echo "Error: No setup.py or pyproject.toml found for building the package."
              exit 1
            fi
            twine check --strict dist/*

        - name: Publish distribution to PyPI
          uses: pypa/gh-action-pypi-publish@release/v1
          with:
            skip-existing: true
            password: ${{ secrets.PYPI_API_TOKEN }} # This token should be created in Settings > Secrets > Actions
            # repository_url: https://test.pypi.org/legacy/ # Use this for testing to upload the distribution to test.pypi

        - name: Determine tag
          id: tag
          run: |
            TAG_NAME=""
            if [[ "${{ github.event.inputs.tag_name }}" != "" ]]; then
              TAG_NAME="${{ github.event.inputs.tag_name }}"
            elif [[ "${{ github.ref }}" == refs/tags/* ]]; then
              TAG_NAME="${GITHUB_REF#refs/tags/}"
            fi

            if [[ -z "$TAG_NAME" ]]; then
              echo "No valid tag provided. Skipping release."
              exit 0
            else
              echo "TAG_NAME=$TAG_NAME" >> $GITHUB_ENV
            fi

        - name: Create/Update GitHub Release
          id: create_update_release
          if: env.TAG_NAME != ''
          uses: ncipollo/release-action@v1
          with:
            tag: ${{ env.TAG_NAME }}
            allowUpdates: true
            omitNameDuringUpdate: true
            makeLatest: true
            artifacts: dist/*